#!/bin/bash
source ${0%/*}/cgi.inc

gm=$(type -P gm) || die "Requires executable gm"

size=$($fbput -q) || die "Can't get framebuffer size"

mono=$media/WenQuanYiMicroHeiMono.ttf
[[ -f $mono ]] || die "Requires $mono"
prop=$media/WenQuanYiMicroHei.ttf
[[ -f $prop ]] || die "Requires $prop"

fg=white
bg=black
point=20
align=nw
font=$mono
command=clear

if (($#)); then
    command=$1
    shift

    for o in "$@"; do
        arg=${o#*=}
        [[ $arg ]] || die "Invalid option $o"
        case $o in
            fg=?*) fg=$arg;;
            bg=?*) bg=$arg;;
            size=?*|point=?*) point=$arg;;
	    align=?*) align=$arg;;
	    mono*) font=$mono;;
	    prop*) font=$prop;;
            badge) point=80; align=c; font=$prop;;
            *) die "Invalid option $o";;
        esac
    done
fi

case $command in
    clear)
        $gm convert -size $size xc:$bg -depth 8 RGB:- | $fbput -
        ;;

    image)
        image=-
        ((${CONTENT_LENGTH:-0})) || image=$media/colorbars.jpg
        $gm convert $image -background $bg -flatten -resize $size! -depth 8 RGB:- | $fbput -
        ;;

    text)
	case $align in
	    nw) gravity=northwest; offset="10, $point" ;;
	    ne) gravity=northeast; offset="10, $point" ;;
            n*) gravity=north;     offset="0,  $point" ;;			
	    w*) gravity=west;      offset="10, $((point/2))" ;;
	    c*) gravity=center;    offset="0,  $((point/2))" ;;
	    e*) gravity=east;      offset="10, $((point/2))" ;;
	    sw) gravity=southwest; offset="10, $((-point))" ;;
	    se) gravity=southeast; offset="10, $((-point))" ;;
	    s*)	gravity=south;     offset="0,  $((-point))" ;;
	    *) Invalid alignment $align;;
  	esac
        tmp=$(mktemp -t display.XXXXXX)
        trap "rm -f $tmp" EXIT
        cat > $tmp
        $gm convert -size $size xc:$bg -fill $fg -font $font -pointsize $point -draw "gravity '$gravity' text $offset '@$tmp'" -depth 8 RGB:- | $fbput -
        ;;

    *) die "Invalid command $command";;
esac
