#!/bin/bash
here=${0%/*}
source $here/cgi.inc

fbput=$here/../fbput/fbput
[ -x $fbput ] || die "Requires executable $fbput"
gm=$(type -P gm) || die "Requires executable gm"

size=$($fbput -q) || die "Can't get framebuffer size"

font=/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
[ -f $font ] || die "Requires $font"

fg=white
bg=black
point=20
gravity=northwest
format=
image=
command=clear

if (($#)); then
    command=$1
    shift

    for o in "$@"; do
        arg=${o#*=}
        [[ $arg ]] || die "Invalid option $o"
        case $o in
            fg=?*) fg=$arg;;
            bg=?*) bg=$arg;;
            point=?*) point=$arg; [[ $point =~ ^[0-9]+$ ]] || die "Invalid point $point";;
            align=l*) gravity=northwest;;
            align=c*) gravity=north;;
            align=r*) gravity=northeast;;
            image=?*) image=$here/$arg; [[ -f $image ]] || die "Invalid image $image";;
            *) die "Invalid option $o";;
        esac
    done
fi

case $command in
    clear)
        $gm convert -size $size "xc:$bg" -depth 8 RGB:- | $fbput -
        ;;

    image)
        if [[ $image ]]; then
            image=$here/$image
        elif ((${CONTENT_LENGTH:-0})); then
            # image is on stdin
            image=-
        else
            image=$here/../colorbars.jpg
        fi
        $gm convert $image -background $bg -flatten -resize $size! -depth 8 RGB:- | $fbput -
        ;;

    text)
        tmp=$(mktemp -t display.XXXXXX)
        trap "rm -f $tmp" EXIT
        cat > $tmp
        $gm convert -size $size xc:$bg -fill $fg -font $font -pointsize $point -draw "gravity '$gravity' text 10,$point '@$tmp'" -depth 8 RGB:- | $fbput -
        ;;

    *) die "Invalid command $command";;
esac
