#!/bin/bash
# return factory server IP and cgi port
here=${0%/*}
source $here/cgi.inc
lookup() { awk 'BEGIN{X=1} {gsub(/[ \t]+/,"");if($1=="'$1'"){print $2; X=0; exit}} END{exit X}' FS== $here/../pionic.cfg; }
echo $(lookup factory_ip)
