#!/bin/bash
# return factory server IP and cgi port
source ${0%/*}/cgi.inc

lookup() { awk 'BEGIN{X=1} {gsub(/[ \t]+/,"");if($1=="'$1'"){print $2; X=0; exit}} END{exit X}' FS== $base/pionic.cfg; }
factory=$(lookup factory_ip)
[[ $factory ]] || die "factory_ip not configured"
echo $factory
