#!/bin/bash
source ${0%/*}/cgi.inc

id -Gn | grep -qw 'root\|gpio' || die "Must be root!"

shopt -s nullglob nocasematch

sys=/sys/class/gpio
[ -d $sys ] || die "User-space GPIOs not supported"

# return list of enabled gpios
enabled()
{
    for f in $sys/gpio[0-9]*; do echo ${f#$sys/gpio}; done | sort -n
}

# set gpio $1 direction to $2, or die
direction()
{
    [ -d $sys/gpio$1 ] || { echo $1 > $sys/export; sleep .1; }
    grep -q $2 $sys/gpio$1/direction || echo $2 > $sys/gpio$1/direction
}

for opt in "$@"; do
    case "$opt" in
        r*)
            for g in $(enabled); do echo $g > $sys/unexport; done
            ;;
        *)
            [[ $opt =~ ^([0-9]+)=(.+) ]] || die "Invalid option '$opt'"
            gpio=${BASH_REMATCH[1]}
            op=${BASH_REMATCH[2]}
            case "$op" in
                0|1)
                    direction $gpio out; echo $op > $sys/gpio$gpio/value
                    ;;
                in*)
                    direction $gpio in
                    ;;
                re*)
                    [ -d $sys/gpio$gpio ] && echo $gpio > $sys/unexport
                    ;;
                *)
                    die "Invalid option '$opt'"
                    ;;
            esac
            ;;
    esac
done

for g in $(enabled); do echo $g: $(cat $sys/gpio$g/direction $sys/gpio$g/value); done
