#!/bin/bash

here=${0%/*}
source $here/cgi.inc

((!UID)) || die "Must be root!"

usage="Usage:

    play [options]
    -or-
    curl http://172.31.255.1/play[?option[&option...]]

Options are:

    video=file  - file to play, default
    time=X      - transmit time in seconds, 0-120, default is 30. 0 just kills the current transmission.
    lcd         - if given, output to lcd instead of hdmi
"

runfor=$here/../runfor/runfor; [ -x $runfor ] || die "Need executable $runfor"

time=30
video=${here}/../colorbars.mp4
display=5

(($#)) && for a in "$@"; do case $a in
    video=*) video=${here}/${a#*=}; [ -f $video ] || die "No such file '$video'";; 
    time=*) time=${a#*=}; echo $time | awk '{exit !(match($1,/^[0-9]+$/) && $1 >= 0 && $1 <= 120)}' || die "Invalid time '$tone'";;
    lcd) display=4;;   
    *) exit 1 # die "$usage"
esac; done    

pkill -f omxplayer || true
if ((time)); then
    echo "Playing $video on display $display for $time seconds"
    # close popen'd stdio or cgiserver will stall
    [ -t 1 ] || exec 0<&- 1>&- 2>&- 3>&- 4>&- 5>&- 6>&- 7>&- 8>&- 9>&-
    # Note must kill fm_transmitter with SIGINT aka signal 2
    ( set +E; $runfor $time omxplayer --display $display --no-keys --no-osd --loop $video & )
fi  
